### ISSUE TITLE
Utilizar Mockups nos testes

### ISSUE THREAD

**Issue by gpupo** [gpupo/submarino-sdk#6]

**Comment by gpupo** [comment]
@danielcosta ,
em https://github.com/gpupo/cnova-sdk/blob/master/tests/Entity/Product/Loads/TestCaseAbstract.php#L30 estou usando uma nova maneira de testar sem executar requisições reais à API, utilizando fixtures para substituição da resposta.

Em Breve implementaremos o mesmo nos testes deste pacote aqui, ok ?

**Comment by danielcosta** [comment]
@gpupo excelente, meu caro!
