### ISSUE TITLE
Novos campos no retorno da Order

### ISSUE THREAD

**Issue by danielcosta** [gpupo/submarino-sdk#9]
Agora na consulta de pedidos são retornados 2 novos campos, são eles:

**purchaseTimestamp** _(string)_: Data e hora de compra no formato: yyyy-mm-dd HH:MM:SS
**lastUpdateTimestamp** _(string)_: Data e hora da última atualização no formato: yyyy-mm-dd HH:MM:SS

Referência: https://api-sandbox.bonmarketplace.com.br/explorer/#!/order/findOrder_get_0

**Comment by danielcosta** [comment]
Já vou adicionar também os campos:

**shipping** *(Shipping)*: Dados referente ao frete,
**paymentMethods** *(array[PaymentMethod])*: Dados referente ao(s) meio(s) de pagamento usado(s) pelo cliente

**Comment by gpupo** [comment]
OK.
Não deixe de adicionar os valores aos JSONs utilizados nos testes unitários.
